services:
  aws:
    build:
      context: ./aws
    environment:
      - LS_LOG=error
      - DEBUG=0
      - ENFORCE_IAM=1
      - SERVICES=iam,s3,dynamodb
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./aws:/etc/localstack/init/ready.d"
      - ./:/monorepo
    networks:
      - bridge-network
    expose:
      - "4566"
    healthcheck:
      test: [
          "CMD-SHELL",
          "curl -s http://localhost:4566/_localstack/init | jq -e '.completed.READY == true'",
        ]
      interval: 5s
      timeout: 10s
      retries: 10

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    develop:
      watch:
        - path: ./server
          action: sync+restart
          target: /app/server
          initial_sync: true
        - path: ./shared
          action: sync+restart
          target: /app/shared
          initial_sync: true
    networks:
      - bridge-network
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      aws:
        condition: service_healthy

  processor:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
    volumes:
      - ./processor/:/app/processor/
      - ./shared/:/app/shared/
    networks:
      - bridge-network
    depends_on:
      aws:
        condition: service_healthy

  engine:
    build:
      context: ./engine
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bridge-network
    expose:
      - "8000"

networks:
  bridge-network:
    driver: bridge
